name: Publish AAR to GitHub Packages

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish (e.g., 1.0.0)'
        required: true
        default: '1.0.0'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        
    - name: Cache Gradle packages
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
          
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Extract version from tag or input
      id: version
      run: |
        if [[ "${{ github.ref }}" == refs/tags/* ]]; then
          VERSION=${GITHUB_REF#refs/tags/v}
        elif [[ "${{ github.event.inputs.version }}" != "" ]]; then
          VERSION=${{ github.event.inputs.version }}
        else
          VERSION="1.0.${{ github.run_number }}"
        fi
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        echo "Publishing version: $VERSION"
        
    - name: Update version in build.gradle.kts
      run: |
        sed -i 's/version = "[^"]*"/version = "${{ steps.version.outputs.version }}"/g' neural-engine/build.gradle.kts
        
    - name: Build and test
      run: ./gradlew :neural-engine:build
      
    - name: Publish to GitHub Packages
      env:
        USERNAME: ${{ github.actor }}
        TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: ./gradlew :neural-engine:publish
      
    - name: Upload AAR artifact
      uses: actions/upload-artifact@v3
      with:
        name: neural-engine-aar
        path: neural-engine/build/outputs/aar/neural-engine-release.aar
        
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Neural Engine v${{ steps.version.outputs.version }}
        body: |
          ## Neural Engine v${{ steps.version.outputs.version }}
          
          ### Installation
          Add this to your app's `build.gradle.kts`:
          
          ```kotlin
          repositories {
              maven {
                  name = "GitHubPackages"
                  url = uri("https://maven.pkg.github.com/monish-instinct/AndroidNeuralEngine")
                  credentials {
                      username = "your-github-username"
                      password = "your-github-token"
                  }
              }
          }
          
          dependencies {
              implementation("com.skynetbee:neural-engine:${{ steps.version.outputs.version }}")
          }
          ```
          
          ### What's Included
          - RFID SDK integration
          - Payment processing
          - Jetpack Compose UI components
          - Multimedia support
          - SQLite encryption
          - And much more!
        draft: false
        prerelease: false

